version: '3.7'

services:
  dev-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "5488:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
